#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Get application name
application=`getApplication`

echo "Running blockMesh"
blockMesh > log.blockMesh

echo "Running setSet"
find -name "*.setSet" -exec setSet -batch {} ';'

echo "Running scalarTransportFoam"
$application > log.scalarTransportFoam &

#echo "Plotting residuals"
#sleep 2
#foamMonitor -l -r 1 postProcessing/residuals/0/residuals.dat

paraFoam -touch
